hpc<-read.table("household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors = FALSE,na.strings="?")
hpc$Time<-strptime(paste(hpc$Date,hpc$Time),"%d/%m/%Y %H:%M:%S")
hpc$Date<-as.Date(hpc$Date,"%d/%m/%Y")
hpcsub<-hpc[hpc$Date==as.Date("2007-2-1") | hpc$Date==as.Date("2007-2-2"),]
png(filename="plot4.png",width = 480, height = 480)
par(mfrow=c(2,2))
plot(hpcsub$Time,hpcsub$Global_active_power,type="l",xlab="",ylab="Global Active Power")
plot(hpcsub$Time,hpcsub$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(hpcsub$Time,hpcsub$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
lines(hpcsub$Time,hpcsub$Sub_metering_2,col="red")
lines(hpcsub$Time,hpcsub$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,bty="n")
plot(hpcsub$Time,hpcsub$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()